---
name: 🌱 Deploy Greenscore Landing on PR 🌱

on:
  pull_request:
    paths:
      - "greenscore-landing/**"

permissions:
  checks: write
  contents: read
  pull-requests: write

concurrency:
  group: greenscore-landing-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Fetch and Build greenscore content
        uses: ./.github/actions/astro
        with:
          token: ${{ secrets.GH_PAT }}
          branch: ${{ github.head_ref || github.ref_name }}
          project-path: greenscore-landing
          output-folder: apigreenscore

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZATSIT_GREENSCORE_STAGING }}
          projectId: zatsit-dsi-externalsites-dev
          target: zatsit-greenscore-d9dfb
          expires: 30d

      # needed to avoid the post action error
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
